# Dataset Related
num_points: 1024  # number of poins actually used in training and evaluation
dataset:
  common:
    NAME: ModelNet40Ply2048
    data_dir: './data/ModelNet40Ply2048'
  train:
    split: train
    num_points: 1024  # in training, use sampled 1024 points for data augmentation.
  val:
    split: test
    num_points: 1024  # in testing, use uniformly pre-sampled 1024 points for evaluation (following https://github.com/lulutang0608/Point-BERT) 

feature_keys: pos

datatransforms:
  train: ['PointsToTensor'] # ['PointsToTensor'] #, 'PointsToTensor', 'PointCloudScaleAndTranslate']
  c: ['TND', 'PointsToTensor', 'PointCloudScaleAndTranslate'] # Spatial_geometry_Enhancement Graph_Domain_Geometry_Enhancement
  vote: [PointCloudScaleAndTranslate]
  val: [PointsToTensor]

  # train: ['TND', 'PointsToTensor', 'PointCloudScaleAndTranslate']
  # c: ['PointsToTensor', 'Graph_Domain_Geometry_Enhancement', 'Spatial_geometry_Enhancement']
  # vote: ['PointCloudScaleAndTranslate']
  # val: ['PointsToTensor']
  kwargs:
    shift: [0.2, 0.2, 0.2]
batch_size: 24
AUG: "ST" # 'cutmix_r' 'cutmix_k' 'mixup' 'rsmix'
dataloader:
  num_workers: 6
  gen_shaply: False
  gen_cam: False
  n_eval: 1000
  shapley: False
  data_index: False # './data/ModelNet40Ply2048/ST_index_pointnet2.npy'
  mask_alpha: 0.2
  gft : False
  shapley_gft : False
  cutoff_frequency : 0.65
  m : None # 'shapely'
  geometry_mode : None # 'SHT'

cut : True # 剪裁特征
num_classes: 40

# ---------------------------------------------------------------------------- #
# Training cfgs
# ---------------------------------------------------------------------------- #
# training receipe borrowed from: https://github.com/yanx27/Pointnet_Pointnet2_pytorch

# ---------------------------------------------------------------------------- #
# Training cfgs
# ---------------------------------------------------------------------------- #
# this one is better.
start_epoch: 0
sched: cosine
epochs: 200 # 600
warmup_epochs: 0
min_lr: null

# Training parameters
lr: 0.001
optimizer:
 NAME: 'adamw'
 weight_decay: 0.05 

grad_norm_clip: 1

criterion_args:
  NAME: JGEKD # SmoothCrossEntropy DKD DML PSKD JGEKD
  label_smoothing: 0.2

# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
log_dir: 'modelnet40'
print_freq: 10
val_freq: 1

# ----------------- Model related
val_batch_size: 32 # 64
# pretrained_path: null

wandb:
  project: PointMetaBase-ModelNet40Ply2048

seed: null

###
mode: train # train test resume
vis: False
# pretrained_path: '/home/liweigang/PointMetaBase/log/modelnet40ply2048/ST_pointnet2/checkpoint/modelnet40ply2048-train-pointnet++-ngpus1-seed9333-20230609-105022-9biiLwRJrF3cANg5PCaRnS_ckpt_best.pth'

modeling:
  # NAME: RandomizedQuantizationAugModule